export const Type = {
  ADD_TASK: 'ADD_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  CHANGE_STATE: 'CHANGE_STATE',
  UPDATE_TASK: 'UPDATE_TASK',
  CHANGE_ORDER: 'CHANGE_ORDER',
  DELETE_DONE: 'DELETE_DONE',
  SWITCH_REMOVE_BTN: 'SWITCH_REMOVE_BTN',
  EDIT_MODE: 'EDIT_MODE'
}
